import { CustomerOrder, WishlistItem, CustomerAddress } from './types';

export const INITIAL_ADDRESSES: CustomerAddress[] = [
  {
    id: 'addr_1',
    fullName: 'Sophia Maharjan',
    phoneNumber: '+977 9841234567',
    streetAddress: 'House 42, Sanepa Marg, Ward 2',
    landmark: 'Near British School',
    city: 'Lalitpur',
    province: 'Bagmati Province',
    postalCode: '44700',
    type: 'home',
    isDefault: true,
  },
  {
    id: 'addr_2',
    fullName: 'Sophia Maharjan',
    phoneNumber: '+977 9801122334',
    streetAddress: 'Level 4, Trade Tower Nepal, Thapathali',
    landmark: 'Opposite to Norvic Hospital',
    city: 'Kathmandu',
    province: 'Bagmati Province',
    postalCode: '44600',
    type: 'work',
    isDefault: false,
  },
];

export const INITIAL_WISHLIST: WishlistItem[] = [
  {
    id: 'wish_1',
    name: 'Bakuchiol & Saffron Glow Youth Nectar',
    category: 'Facial Serum',
    volume: '30 ml / 1.0 fl. oz',
    price: 3450,
    originalPrice: 3800,
    image: '/images/products/product-1.png',
    slug: 'bakuchiol-saffron-glow-youth-nectar',
    inStock: true,
    keyBotanicals: ['Himalayan Saffron', 'Plant Bakuchiol', 'Cold-Pressed Rosehip'],
    addedAt: '2026-03-24',
  },
  {
    id: 'wish_2',
    name: 'Kumkumadi Restorative Night Infusion',
    category: 'Botanical Elixir',
    volume: '50 ml / 1.7 fl. oz',
    price: 4200,
    originalPrice: 4600,
    image: '/images/products/pdt-2.png',
    slug: 'kumkumadi-restorative-night-infusion',
    inStock: true,
    keyBotanicals: ['Kashmir Saffron', 'Red Sandalwood', 'Lotus Stamen'],
    addedAt: '2026-03-20',
  },
  {
    id: 'wish_3',
    name: 'Gotu Kola & Green Tea Balancing Toner',
    category: 'Clarifying Essence',
    volume: '150 ml / 5.1 fl. oz',
    price: 1950,
    originalPrice: 2200,
    image: '/images/products/pdt-4.png',
    slug: 'gotu-kola-green-tea-balancing-toner',
    inStock: false,
    keyBotanicals: ['Centella Asiatica', 'Organic Green Tea', 'Vetiver Root'],
    addedAt: '2026-03-15',
  },
];

export const INITIAL_ORDERS: CustomerOrder[] = [
  {
    id: 'ord_1',
    orderNumber: 'GV-2026-8942',
    createdAt: '2026-03-28T09:42:00Z',
    status: 'PROCESSING',
    subtotal: 5400,
    shippingFee: 0,
    discount: 500,
    total: 4900,
    paymentMethod: 'KHALTI',
    paymentStatus: 'PAID',
    trackingNumber: 'GV-TRK-7849102',
    estimatedDelivery: 'March 31, 2026',
    shippingAddress: INITIAL_ADDRESSES[0],
    items: [
      {
        id: 'item_1',
        name: 'Bakuchiol & Saffron Glow Youth Nectar',
        category: 'Facial Serum',
        volume: '30 ml',
        price: 3450,
        quantity: 1,
        image: '/images/products/product-1.png',
        slug: 'bakuchiol-saffron-glow-youth-nectar',
      },
      {
        id: 'item_2',
        name: 'Gotu Kola & Green Tea Balancing Toner',
        category: 'Clarifying Essence',
        volume: '150 ml',
        price: 1950,
        quantity: 1,
        image: '/images/products/pdt-4.png',
        slug: 'gotu-kola-green-tea-balancing-toner',
      },
    ],
  },
  {
    id: 'ord_2',
    orderNumber: 'GV-2026-7821',
    createdAt: '2026-03-12T14:15:00Z',
    status: 'DELIVERED',
    subtotal: 4200,
    shippingFee: 150,
    discount: 0,
    total: 4350,
    paymentMethod: 'CARD',
    paymentStatus: 'PAID',
    trackingNumber: 'GV-TRK-4321098',
    deliveredAt: 'March 15, 2026',
    shippingAddress: INITIAL_ADDRESSES[0],
    items: [
      {
        id: 'item_3',
        name: 'Kumkumadi Restorative Night Infusion',
        category: 'Botanical Elixir',
        volume: '50 ml',
        price: 4200,
        quantity: 1,
        image: '/images/products/pdt-2.png',
        slug: 'kumkumadi-restorative-night-infusion',
      },
    ],
  },
  {
    id: 'ord_3',
    orderNumber: 'GV-2026-6105',
    createdAt: '2026-02-18T11:20:00Z',
    status: 'DELIVERED',
    subtotal: 2800,
    shippingFee: 0,
    discount: 280,
    total: 2520,
    paymentMethod: 'ESEWA',
    paymentStatus: 'PAID',
    trackingNumber: 'GV-TRK-1098321',
    deliveredAt: 'February 21, 2026',
    shippingAddress: INITIAL_ADDRESSES[1],
    items: [
      {
        id: 'item_4',
        name: 'Vetiver & Sacred Lotus Cleansing Emulsion',
        category: 'Purifying Cleanser',
        volume: '120 ml',
        price: 2800,
        quantity: 1,
        image: '/images/products/pdt-4.png',
        slug: 'vetiver-sacred-lotus-cleansing-emulsion',
      },
    ],
  },
];
